name: CI Frontend

on:
  pull_request:
    branches: [ main, develop, qa ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npx vue-tsc --noEmit

      - name: Build app
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
      - name: Start app
        run: npm run preview &

      - name: Wait for app
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run Cypress
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: http://localhost:4173
          CYPRESS_STUDENT_EMAIL: ${{ secrets.CYPRESS_STUDENT_EMAIL }}
          CYPRESS_STUDENT_PASSWORD: ${{ secrets.CYPRESS_STUDENT_PASSWORD }}
          CYPRESS_PROFESSOR_EMAIL: ${{ secrets.CYPRESS_PROFESSOR_EMAIL }}
          CYPRESS_PROFESSOR_PASSWORD: ${{ secrets.CYPRESS_PROFESSOR_PASSWORD }}
          CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
          CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}

      - name: Upload Cypress artifacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-evidence
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7