name: CI Frontend

on:
  pull_request:
    branches: [ main, develop, qa ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm run preview &

      - name: Wait for app
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run Cypress
        run: npx cypress run
        env:
          VITE_API_URL: https://sgea-backend-production.up.railway.app/api/v1
          CYPRESS_BASE_URL: http://localhost:4173
          CYPRESS_STUDENT_EMAIL: estudiante1@test.com
          CYPRESS_STUDENT_PASSWORD: contraseñaAdmin01
          CYPRESS_PROFESSOR_EMAIL: docente1@test.com
          CYPRESS_PROFESSOR_PASSWORD: contraseñaAdmin01
